=== vivekanandareddy95/COVAXSYSBACKEND/covaxsys/src/main/resources/api/datatypes/PostUsersRequest.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "hcn": {
      "type": "string"
    },
    "dob": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "address": {
      "type": "string"
    },
    "address2": {
      "type": "string"
    },
    "postalCode": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "serviceType": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "dateSlot": {
      "type": "string"
    },
    "timeSlot": {
      "type": "string"
    }
  },
  "required": [
]
}

=== vivekanandareddy95/COVAXSYSBACKEND/covaxsys/src/main/resources/api/examples/PostShoppingRequest.json
{
      "firstName":"Vivek",
      "lastName":"Reddy",
      "hcn":"98765",
      "dob":"2/1/2000",
      "email":"email156@gmail.com",
      "address":"123 streetName",
      "address2":"8",
      "postalCode":"h2k 9p2",
      "city":"Montreal",
      "country":"Canada",
      "serviceType":"Covid-19 vaccin - 2nd dose",
      "location":"Location 1",
      "dateSlot":"2021-06-25",
      "timeSlot":"8:30am - 8:45am"
}
